/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef PEANUTLABS_AUTODEFS_H
#define PEANUTLABS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_PEANUTLABS_NAME "peanutlabs"
#define S3E_EXT_PEANUTLABS_HASH 0xa13945f4

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("peanutlabs", 1)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !PEANUTLABS_AUTODEFS_H */
