/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "peanutlabs_autodefs.h"
#include "s3eEdk.h"
#include "peanutlabs.h"
//Declarations of Init and Term functions
extern s3eResult peanutlabsInit();
extern void peanutlabsTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult openRewardsCenter_wrap(const char* user_id)
{
    IwTrace(PEANUTLABS_VERBOSE, ("calling peanutlabs func on main thread: openRewardsCenter"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)openRewardsCenter, 1, user_id);
}

#define openRewardsCenter openRewardsCenter_wrap


#endif

void peanutlabsRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[1];
    funcPtrs[0] = (void*)openRewardsCenter;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[1] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("peanutlabs", funcPtrs, sizeof(funcPtrs), flags, peanutlabsInit, peanutlabsTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int peanutlabsStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&peanutlabsRegisterExt;
    return 0;
}

int g_peanutlabsVal = peanutlabsStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    peanutlabsRegisterExt();
}
#endif

#endif
